apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: locust-master
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 8089
    - name: master
      protocol: TCP
      port: 5557
      targetPort: 5557
    - name: master1
      protocol: TCP
      port: 5558
      targetPort: 5558